title: Cesar Nasr # your name (or website title) here
logo: "/images/logo.png?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  <b><h2> Mobile Developer </h2></b>
  <br>
  <b>Contact:</b>
  <br>
  Email: <a target="_blank" href = "mailto: Cesarjnasr@gmail.com">Cesarjnasr@gmail.com</a>
  <br>
  Phone: <a target="_blank" href="tel:+96171103488">+96171103488</a>
  <br>
  <a target="_blank" href="https://drive.google.com/file/d/1YHJg1ezZb0fkkGMVxZHKZKNVHS0gsP8s/view">View My Resume</a>
  <br>
  <a target="_blank" href="https://www.linkedin.com/in/cesar-nasr-32209bb9/">View My LinkedIn Profile</a> 
  <br>
  <a target="_blank" href="https://github.com/CesarNasr">View My Github Profile</a> 
  
theme: jekyll-theme-minimal
# google_analytics: UA-000000-0 # your Google Analytics tracking ID here
